#+TITLE: lan-mouse monitor for laptops (client)
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :tangle lanmouse-monitor_laptop.sh
#+DESCRIPTION: monitor lan-mouse logs and run appropriate commands on laptops (client)
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc_3:
- [[#header][Header]]
- [[#variables][Variables]]
- [[#monitoring][Monitoring]]
  - [[#connection-stablished][Connection stablished]]
  - [[#connection-interrupted][Connection interrupted]]
  - [[#keyboard-and-mouse-leaving-host][Keyboard and mouse LEAVING host]]
  - [[#keyboard-and-mouse-entering-host][Keyboard and mouse ENTERING host]]
  - [[#eos][EoS]]

* Header :noexport_1:
** Shebang
#+begin_src sh
#!/usr/bin/env bash
#+end_src
** Description
#+begin_src sh
# description:
#   script to share clipboard via lan-mouse (software KVM) with the sender host.
# how it works:
#   it monitors the output of the journal for the lan-mouse unit, and once it 
#   detects that the cursor moved back to the sender, it runs push-clipboard.sh
#   script that sends the clipboard back via SSH forced commands (previously 
#   configured in ~/.ssh/authorized-keys).
#+end_src
** Help menu
#+begin_src sh
# Usage:
#   This is script is meant to be used as a daemon. A systemd user service
#   is responsible for launching and controlling it.
#+end_src
* Variables
#+begin_src sh
# define systemd unit to monitor
UNIT="lanmouse"
STATUS_FILE="/tmp/lanmouse-status.tmp"

# define messages to monitor on the output of journalctl
TRIGGER_CONNECTION="lan_mouse::listen] dtls client connected, ip: "
TRIGGER_DISCONNECTION_START="lan_mouse::emulation] releasing keys: "
TRIGGER_DISCONNECTION_END=" not responding!"
TRIGGER_ENTERING_START="releasing capture: "
TRIGGER_ENTERING_END=" entered this device"
TRIGGER_LEAVING="releasing capture: no active client at this position"

# set cooldown (in miliseconds) to avoid double trigger
COOLDOWN=250
LAST_TRIGGER=0
#+end_src
* Monitoring
#+begin_src sh
# monitor the journal for the specific user unit
journalctl --user -u "$UNIT" -f -n 0 | cat | while read -r line; do
CURRENT_TIME=$(($(date +%s%N)/1000000))
case "$line" in
#+end_src
** Connection stablished
#+begin_src sh
,*"$TRIGGER_CONNECTION"*)
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Connection stablished. Setting Sway scale and updating lanmouse-status file."
    # adjust Sway scale
    swaymsg exec $XDG_CONFIG_HOME/scripts/sway-scale.sh 1.25
    echo "connected" > $STATUS_FILE
    ;;
#+end_src
** Connection interrupted
#+begin_src sh
,*"$TRIGGER_DISCONNECTION_START"*"$TRIGGER_DISCONNECTION_END"*)
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Connection stablished. Resetting Sway scale and updating lanmouse-status file."
    # adjust Sway scale
    swaymsg exec $XDG_CONFIG_HOME/scripts/sway-scale.sh 1.00
    echo "disconnected" > $STATUS_FILE
    ;;
#+end_src
** Keyboard and mouse LEAVING host
Leaving laptop. Share clipboard with sender.
  - laptop --> desktop
  - client --> server
  - receiving --> sender
#+begin_src sh
# leaving this host --> returning to desktop
,*"$TRIGGER_LEAVING"*)
    # check if enough time (cooldown) has passed since the last trigger
    if (( CURRENT_TIME - LAST_TRIGGER >= COOLDOWN )); then
        echo -n "[$(date '+%Y-%m-%d %H:%M:%S')] Mouse returned to PC. Sending clipboard and re-enabling xremap default mode..."
        # send clipboard via SSH forced command
        $HOME/.config/scripts/push-clipboard.sh catuaba > /dev/null
        # re-enable xremap's default mode (FN_F2)
        ssh catuaba "ydotool key 467:1 467:0"
        # append "Done!" or "Failed!" to the previous line according to the script status
        [ $? -eq 0 ] && echo " Done!" || echo " Failed!"
        LAST_TRIGGER=$CURRENT_TIME

        # update status file
        echo "connected" > $STATUS_FILE
    fi
    ;;
#+end_src
** Keyboard and mouse ENTERING host
Entering laptop. No functionality yet.
  - desktop --> laptop
  - server --> client
  - sender --> receiving
#+begin_src sh
# entering this host
,*"$TRIGGER_ENTERING_START"*"$TRIGGER_ENTERING_END"*)
    # update status file
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Mouse entered in client. Updating lan-mouse status file."
    echo "active" > $STATUS_FILE
    ;;
#+end_src
** EoS
#+begin_src sh
esac
done
#+end_src
