#+TITLE: Config file for LogiOps
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :tangle logid.cfg
#+DESCRIPTION: config file for LogiOps
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc_4:
- [[#devices][Devices]]
  - [[#mx-master-3][MX Master 3]]
    - [[#buttons][Buttons]]
    - [[#documentation][Documentation]]
      - [[#general][General]]
      - [[#thumb-wheel][Thumb wheel]]
      - [[#side-bottom][Side-bottom]]
      - [[#side-top][Side-top]]
      - [[#gesture-button][Gesture button]]
      - [[#mode-shift][Mode shift]]
    - [[#settings][Settings]]
    - [[#thumb-wheel-1][Thumb wheel]]
    - [[#buttons-1][Buttons]]
      - [[#magspeed-scroll-wheel][MagSpeed scroll wheel]]
      - [[#side-top-1][Side-top]]
      - [[#side-bottom-1][Side-bottom]]
      - [[#mode-shift-1][Mode shift]]
      - [[#gesture-button-1][Gesture button]]
      - [[#switch-receivers][Switch receivers]]
  - [[#mx-keys][MX Keys]]
    - [[#name--buttons][Name & Buttons]]
    - [[#f-keys][F-keys]]
    - [[#easy-switch][Easy-Switch]]
    - [[#numpad][Numpad]]
    - [[#arrows][Arrows]]

* Devices
#+begin_src conf
devices: (
#+end_src
** MX Master 3
*** Buttons
|----------------------+--------------+------+---------|
| Physical Action      | xbindkeys    | CID  | gesture |
|----------------------+--------------+------+---------|
| left button          | button 1     | ---- | ---     |
| MagSpeed wheel       | button 2     | 0x52 | yes     |
| right button         | button 3     | ---- | ---     |
| scroll Y wheel up    | button 4     | ---- | ---     |
| scroll Y wheel down  | button 5     | ---- | ---     |
| scroll X wheel right | button 6     | ---- | ---     |
| scroll X wheel left  | button 7     | ---- | ---     |
| side-bottom button   | button 8     | 0x53 | yes     |
| side-top button      | button 9     | 0x56 | yes     |
| gesture button       | C-A-Tab      | 0xc3 | yes     |
|----------------------+--------------+------+---------|
| mode shift           | not detected | 0xc4 | yes     |
|----------------------+--------------+------+---------|
| switch receivers     | ----         | 0xd7 | yes     |
|----------------------+--------------+------+---------|
Obs.: function names from https://github.com/PixlOne/logiops/wiki/CIDs
*** Documentation
**** General
|---------------+------------|
| Keybindings   | Function   |
|---------------+------------|
| left button   | unchanged  |
| right button  | unchanged  |
| middle button | BTN_MIDDLE |
|---------------+------------|
**** Thumb wheel
|-------------+---------------------------------|
| Keybindings | Function                        |
|-------------+---------------------------------|
| wheel left  | REL_HWHEEL (multiplier -0.5)    |
| wheel right | REL_HWHEEL (multiplier +0.5)    |
| tap wheel   | Super-Alt-F (toggle fullscreen) |
|-------------+---------------------------------|
**** Side-bottom
|----------------------------------+--------------------------------------|
| Keybindings                      | Function                             |
|----------------------------------+--------------------------------------|
| side-bottom                      | BTN_BACK (tap: PageDown / hold: F21) |
| side-bottom + wheel down         | vol-                                 |
| side-bottom + wheel up           | vol+                                 |
| side-bottom + left click         | vol- (prev 25%)                      |
| side-bottom + right click        | vol+ (next 25%)                      |
| side-bottom + middle click       |                                      |
|----------------------------------+--------------------------------------|
| side-bottom + mode shift (click) |                                      |
| side-bottom + mode shift (down)  |                                      |
| side-bottom + mode shift (up)    |                                      |
| side-bottom + mode shift (left)  |                                      |
| side-bottom + mode shift (right) |                                      |
|----------------------------------+--------------------------------------|
**** Side-top
|-------------------------------+---------------------------------------|
| Keybindings                   | Function                              |
|-------------------------------+---------------------------------------|
| side-top                      | BTN_FORWARD (tap: PageUp / hold: F22) |
| side-top + wheel down         | zoom-                                 |
| side-top + wheel up           | zoom+                                 |
| side-top + left click         | ws prev                               |
| side-top + right click        | ws next                               |
| side-top + middle click       |                                       |
|-------------------------------+---------------------------------------|
| side-top + mode shift (click) |                                       |
| side-top + mode shift (down)  |                                       |
| side-top + mode shift (up)    |                                       |
| side-top + mode shift (left)  |                                       |
| side-top + mode shift (right) |                                       |
|-------------------------------+---------------------------------------|
**** Gesture button
|------------------------------+---------------------------------|
| Keybindings                  | Function                        |
|------------------------------+---------------------------------|
| gesture                      | BTN_SIDE (tap: ??? / hold: F23) |
| gesture + wheel down         | brightness- (coarse)            |
| gesture + wheel up           | brightness+ (coarse)            |
| gesture + left click         |                                 |
| gesture + right click        |                                 |
| gesture + middle click       |                                 |
| gesture + mode shift         |                                 |
|------------------------------+---------------------------------|
| gesture + mode shift (click) |                                 |
| gesture + mode shift (down)  |                                 |
| gesture + mode shift (up)    |                                 |
| gesture + mode shift (left)  |                                 |
| gesture + mode shift (right) |                                 |
|------------------------------+---------------------------------|
**** Mode shift
|----------------------------------+---------------------------------------|
| Keybindings                      | Function                              |
|----------------------------------+---------------------------------------|
| mode shift                       | Enter                                 |
| mode shift + down                | F17 (copy)                            |
| mode shift + up                  | F18 (paste)                           |
| mode shift + left                | S-n (go back in browser history)      |
| mode shift + right               | S-o (go forward browser history)      |
|----------------------------------+---------------------------------------|
*** logid -v :noexport:
#+begin_src txt :tangle no:
    #[DEBUG] Unsupported device /dev/hidraw0 ignored
    #[INFO] Device found: Wireless Mouse MX Master 3 on /dev/hidraw1:255
    #[DEBUG] /dev/hidraw1:255 remappable buttons:
    #[DEBUG] CID  | reprog? | fn key? | mouse key? | gesture support?
    #[DEBUG] 0x50 |         |         | YES        | 
    #[DEBUG] 0x51 |         |         | YES        | 
    #[DEBUG] 0x52 | YES     |         | YES        | YES
    #[DEBUG] 0x53 | YES     |         | YES        | YES
    #[DEBUG] 0x56 | YES     |         | YES        | YES
    #[DEBUG] 0xc3 | YES     |         | YES        | YES
    #[DEBUG] 0xc4 | YES     |         | YES        | YES
    #[DEBUG] 0xd7 | YES     |         |            | YES
    #[DEBUG] Thumb wheel detected (0x2150), capabilities:
    #[DEBUG] timestamp | touch | proximity | single tap
    #[DEBUG] YES       | YES   | YES       | YES       
    #[DEBUG] Thumb wheel resolution: native (18), diverted (120)
#+end_src
*** Settings :noexport_1:
**** Name
#+begin_src conf
  {name: "Wireless Mouse MX Master 3";
#+end_src
**** DPI
Change mouse default dpi.
#+begin_src conf
    dpi: 1500;              # 200 to 4000
#+end_src
**** SmartShift
Cchange wheel mode from ratchet to free-spin.
#+begin_src conf
    smartshift: {
      on: true              # false to free-spin
      threshold: 20         # 1~255
    };
#+end_src
**** HiRes
Defines the HiRes mouse-scrolling.
#+begin_src conf
    hiresscroll: {
      hires: true
      invert: false
      target: false         # HID++ notification or normal
    };
#+end_src
*** Thumb wheel :noexport_1:
#+begin_src conf
    thumbwheel: {
      divert: true          # enable/disable
      invert: false
#+end_src
**** Right
#+begin_src conf
      right: {
        mode: "Axis"
        axis: "REL_HWHEEL"
        axis_multiplier: 0.5
      }
#+end_src
**** Left
#+begin_src conf
      left: {
        mode: "Axis"
        axis: "REL_HWHEEL"
        axis_multiplier: -0.5
      }
#+end_src
**** Proxy
Action when thumb is near the thumb wheel.
#+begin_src conf
#      proxy: {
#        type: "ToggleSmartshift"
#      }
#+end_src
**** Tap
Action when thumb button is tapped.
#+begin_src conf
      tap: {
        type: "KeyPress" 
        keys: ["KEY_LEFTMETA", "KEY_LEFTALT", "KEY_F"]
      }
#+end_src
**** Touch
Gestures for thumb wheel.
#+begin_src conf
#      touch: {
#        type: "Gestures"
#        gestures: (
#+end_src
***** Down
#+begin_src conf
#          {
#            direction: "Down"
#            threshold: 50
#            mode: "OnRelease"
#            action: {
#              type: "KeyPress"
#              keys: ["KEY_A"]
#            }
#          },
#+end_src
***** Up
#+begin_src conf
#          {
#            direction: "Up"
#            threshold: 50
#            mode: "OnRelease"
#            action: {
#              type: "KeyPress"
#              keys: ["KEY_B"]
#            }
#          },
#+end_src
***** Left
#+begin_src conf
#          {
#            direction: "Left"
#            threshold: 50
#            mode: "OnRelease"
#            action: {
#              type: "KeyPress"
#              keys: ["KEY_C"]
#            }
#          },
#+end_src
***** Right
#+begin_src conf
#          {
#            direction: "Right"
#            threshold: 50
#            mode: "OnRelease"
#            action: {
#              type: "KeyPress"
#              keys: ["KEY_D"]
#            }
#          },
#+end_src
***** None
#+begin_src conf
#          {
#            direction: "None"
#            mode: "OnRelease"
#            action: {
#              type: "KeyPress"
#              keys: ["KEY_E"]
#            }
#          },
#+end_src
***** EoS
#+begin_src conf
#        )
#      }
    };
#+end_src
*** Buttons
#+begin_src conf
    buttons: (
#+end_src
**** MagSpeed scroll wheel
#+begin_src conf
      {cid: 0x52
        action = {
          type: "KeyPress"
          keys: ["BTN_MIDDLE"]
        }
      },
#+end_src
**** Side-top
#+begin_src conf
      {cid: 0x56
        action = {
          type: "KeyPress"
          keys: ["BTN_FORWARD"]
        }
      },
#+end_src
**** Side-bottom
#+begin_src conf
      {cid: 0x53
        action = {
          type: "KeyPress"
          keys: ["BTN_BACK"]
        }
      },
#+end_src
**** Mode shift
#+begin_src conf
      {cid: 0xc4
        action = {
          type: "Gestures"
          gestures: (
#+end_src
***** Down
#+begin_src conf
            {
              direction: "Down"
              threshold: 50
              mode: "OnRelease"
              action: {
                type: "KeyPress" 
                # binded to "copy" in xremap
                keys: ["KEY_F17"]
              }
            },
#+end_src
***** Up
#+begin_src conf
            {
              direction: "Up"
              threshold: 50
              mode: "OnRelease"
              action: {
                type: "KeyPress" 
                # binded to "paste" in xremap
                keys: ["KEY_F18"]
              }
            },
#+end_src
***** Left
#+begin_src conf
            {
              direction: "Left"
              threshold: 50
              mode: "OnRelease"
              action: {
                type: "KeyPress"
                # used in web browser to navigate to previous page in history
                keys: ["KEY_LEFTSHIFT", "KEY_N"]
              }
            },
#+end_src
***** Right
#+begin_src conf
            {
              direction: "Right"
              threshold: 50
              mode: "OnRelease"
              action: {
                type: "KeyPress"
                # used in web browser to navigate to next page in history
                keys: ["KEY_LEFTSHIFT", "KEY_O"]
              }
            },
#+end_src
***** None
#+begin_src conf
            {
              direction: "None"
              mode: "OnRelease"
              action: {
                type: "KeyPress" 
                keys: ["KEY_ENTER"]
              }
            },
#+end_src
***** EoS
#+begin_src conf
          )
        }
      },
#+end_src
**** Gesture button
***** KeyPress
#+begin_src conf
      {cid: 0xc3
        action = {
          type: "KeyPress"
          keys: ["BTN_SIDE"]
        }
      },
#+end_src
**** Switch receivers
#+begin_src conf :tangle no:
      {cid: 0xd7
        action = {
          type: "KeyPress"
          keys: ["KEY_UNKNOWN"]
        }
      },
#+end_src
*** EoS :noexport:
#+begin_src conf
    )
  },
#+end_src
** MX Keys
|----------------+-----------+------|
| Key            | xbindkeys |  CID |
|----------------+-----------+------|
| F1             |           | 0xc7 |
| F2             |           | 0xc8 |
| F3             |           | 0xe0 |
| F4             |           | 0xe1 |
| F5             |           | 0x6e |
| F6             |           | 0xe2 |
| F7             |           | 0xe3 |
| F8             |           | 0xe4 |
| F9             |           | 0xe5 |
| F10            |           | 0xe6 |
| F11            |           | 0xe7 |
| F12            |           | 0xe8 |
| Volume Up      |           | 0xe9 |
|----------------+-----------+------|
| Easy-Switch #1 |           | 0xd1 |
| Easy-Switch #2 |           | 0xd2 |
| Easy-Switch #3 |           | 0xd3 |
|----------------+-----------+------|
| Calculator     |           | 0x0a |
| Camera         |           | 0xbf |
| Menu           |           | 0xea |
| Lock Screen    |           | 0x6f |
|----------------+-----------+------|
| Right arrow    |           | 0xeb |
| Left arrow     |           | 0xec |
|----------------+-----------+------|
*** logid -v :noexport:
#+begin_src txt
    # logid -v
    #[INFO] Device found: MX Keys Wireless Keyboard on /dev/hidraw0:2
    #[DEBUG] /dev/hidraw0:2 remappable buttons:
    #[DEBUG] CID  | reprog? | fn key? | mouse key? | gesture support?
    #[DEBUG] 0x0a | YES     |         |            | 
    #[DEBUG] 0x34 |         |         |            | 
    #[DEBUG] 0x6e | YES     | YES     |            | 
    #[DEBUG] 0x6f | YES     |         |            | 
    #[DEBUG] 0xbf | YES     |         |            | 
    #[DEBUG] 0xc7 | YES     | YES     |            | 
    #[DEBUG] 0xc8 | YES     | YES     |            | 
    #[DEBUG] 0xd1 | YES     |         |            | 
    #[DEBUG] 0xd2 | YES     |         |            | 
    #[DEBUG] 0xd3 | YES     |         |            | 
    #[DEBUG] 0xde |         | YES     |            | 
    #[DEBUG] 0xe0 | YES     | YES     |            | 
    #[DEBUG] 0xe1 | YES     | YES     |            | 
    #[DEBUG] 0xe2 | YES     | YES     |            | 
    #[DEBUG] 0xe3 | YES     | YES     |            | 
    #[DEBUG] 0xe4 | YES     | YES     |            | 
    #[DEBUG] 0xe5 | YES     | YES     |            | 
    #[DEBUG] 0xe6 | YES     | YES     |            | 
    #[DEBUG] 0xe7 | YES     | YES     |            | 
    #[DEBUG] 0xe8 | YES     | YES     |            | 
    #[DEBUG] 0xe9 | YES     |         |            | 
    #[DEBUG] 0xea | YES     |         |            | 
    #[DEBUG] 0xeb | YES     |         |            | 
    #[DEBUG] 0xec | YES     |         |            | 
#+end_src
*** Name & Buttons
#+begin_src conf
  {name: "MX Keys Wireless Keyboard";

    buttons: (
#+end_src
*** F-keys :noexport_1:
**** F1
F1 key: Screen Brightness Down
#+begin_src conf
      {cid: 0x00c7;
        action = {
          type : "Keypress";
          keys: ["KEY_BRIGHTNESSDOWN"];
          #XF86MonBrightnessDown (keycode 232)
        };
      },
#+end_src
**** F2
F2 key: Screen Brightness Up
#+begin_src conf
      {cid: 0x00c8;
        action = {
          type : "Keypress";
          #keys: ["KEY_BRIGHTNESSUP"];
          keys: ["KEY_F2"];
          #XF86MonBrightnessUp (keycode 233)
        };
      },
#+end_src
**** F3
#+begin_src conf
      #{cid: 0xe0;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_F3"];
      #  };
      #},
#+end_src
**** F4
#+begin_src conf
      {cid: 0xe1;
        action = {
          type : "Keypress";
          keys: ["KEY_F4"];
          #keys: ["KEY_CLOSE"];
          # XF86Close (keycode 214)
        };
      },
#+end_src
**** F5
#+begin_src conf
      {cid: 0x6e;
        action = {
          type : "Keypress";
          keys: ["KEY_F5"];
        };
      },
#+end_src
**** F6
F6 key: Backlight Brightness Down
#+begin_src conf
      {cid: 0xe2;
        action = {
          type : "Keypress";
          keys: ["KEY_KBDILLUMDOWN"];
          #XF86KbdBrightnessDown (keycode 237)
        };
      },
#+end_src
**** F7
F7 key: Backlight Brightness Up
#+begin_src conf
      {cid: 0xe3;
        action = {
          type : "Keypress";
          keys: ["KEY_KBDILLUMUP"];
          #XF86KbdBrightnessUp (keycode 238)
        };
      },
#+end_src
**** F8
#+begin_src conf
      {cid: 0xe4;
        action = {
          type : "Keypress";
          keys: ["KEY_PREVIOUSSONG"];
          #XF86AudioPrev (keycode 173)
        };
      },
#+end_src
**** F9
#+begin_src conf
      {cid: 0xe5;
        action = {
          type : "Keypress";
          keys: ["KEY_PLAYPAUSE"];
          #XF86AudioPlay (keycode 172)
        };
      },
#+end_src
**** F10
#+begin_src conf
      {cid: 0xe6;
        action = {
          type : "Keypress";
          keys: ["KEY_NEXTSONG"];
          #XF86AudioNext (keycode 171)
        };
      },
#+end_src
**** F11
#+begin_src conf
      {cid: 0xe7;
        action = {
          type : "Keypress";
          keys: ["KEY_MUTE"];
        };
      },
#+end_src
**** F12
#+begin_src conf
      {cid: 0xe8;
        action = {
          type : "Keypress";
          keys: ["KEY_VOLUMEDOWN"];
        };
      },
#+end_src
**** Volume Up
#+begin_src conf
      {cid: 0xe9;
        action = {
          type : "Keypress";
          keys: ["KEY_VOLUMEUP"];
        };
      },
#+end_src
*** Easy-Switch :noexport_1:
**** Easy-Switch #1
#+begin_src conf
      #{cid: 0xd1;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_MACRO1"];
      #  };
      #},
#+end_src
**** Easy-Switch #2
#+begin_src conf
      #{cid: 0xd2;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_MACRO2"];
      #  };
      #},
#+end_src
**** Easy-Switch #3
#+begin_src conf
      {cid: 0xd3;
        action = {
          type : "Keypress";
          keys: ["KEY_F13"];
        };
      },
#+end_src
*** Numpad :noexport_1:
**** Calculator
#+begin_src conf
      {cid: 0x0a;
        action = {
          type : "Keypress";
          keys: ["KEY_CALC"];
          #XF86Calculator (keycode 148)
        };
      },
#+end_src
**** Camera
#+begin_src conf
      #{cid: 0xbf;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_SCREENSAVER"];
      #  };
      #},
#+end_src
**** Menu
#+begin_src conf
      #{cid: 0xea;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_CONTEXT_MENU"];
      #  };
      #},
#+end_src
**** Lock Screen
#+begin_src conf
      {cid: 0x6f;
        action = {
          type : "Keypress";
          #keys: ["KEY_SCREENLOCK"];
          keys: ["KEY_COFFEE"];
          #XF86ScreenSaver (keycode 160)
        };
      },
#+end_src
*** Arrows :noexport_1:
**** Right
#+begin_src conf
      #{cid: 0xeb;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_RIGHT"];
      #  };
      #},
#+end_src
**** Left
#+begin_src conf
      #{cid: 0xec;
      #  action = {
      #    type : "Keypress";
      #    keys: ["KEY_LEFT"];
      #  };
      #}
#+end_src
**** EoS
#+begin_src conf
    )
  }
);
#+end_src
