#+TITLE: X.Org related files
#+AUTHOR: Rafael Ito
#+DESCRIPTION: X.Org related files
#+STARTUP: showeverything

* Table of contents :toc_1:
- [[#summary][Summary]]
- [[#xbindkeys][xbindkeys]]
- [[#xcape][xcape]]

* Summary
|------------------+---------------------+------------------------------------------------|
| File in this dir | Destination path    | Description                                    |
|------------------+---------------------+------------------------------------------------|
| xbindkeysrc      | ~/.xbindkeysrc      | xbindkeys dotfile (map keys to commands).      |
| XCompose         | ~/.XCompose         | custom key combinations for special characters |
| Xmodmap          | ~/.Xmodmap          | File to alter keymaps (current version).       |
| Xmodmap_original | ~/.Xmodmap_original | File to alter keymaps (original backup).       |
| Xmodmap_numbers  | ~/.Xmodmap_numbers  | File to alter keymaps (with numpad layer).     |
| xcape            | /usr/bin/xcape      | Makes modifiers act as keys when tapped.       |
| xprofile         | ~/.xprofile         | Startup commands for display managers.         |
|------------------+---------------------+------------------------------------------------|
* xbindkeys
** Using Press & Release
Check documentation:
http://xmacro.sourceforge.net/

#+begin_src sh
"(echo "KeyCodePress 36" | xmacroplay) && (echo "KeyCodeRelease 36" | xmacroplay)"
#+end_src
** Custom key combinations
For more informations:
http://xahlee.info/linux/linux_xvkbd_tutorial.html
*** Ctrl + ":" --> KEY_SEMICOLON
#+begin_src sh
"xvkbd -xsendevent -text ";""
    Control + semicolon
    #m:0x4 + c:47
#+end_src
*** Ctrl + KEY_0 --> KEY_HOME
#+begin_src sh
#"xvkbd -xsendevent -text "\[Home]""
#    Control + 0
#+end_src
*** Ctrl + KEY_4 --> KEY_END
#+begin_src sh
#"xvkbd -xsendevent -text "\[End]""
#    Control + 4
#+end_src
** Volume control with the mouse
*** Volume up
#+begin_src sh
"pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-volume {} +5% && pkill -RTMIN+1 i3blocks"
Alt + b:4
#+end_src
*** Volume down
#+begin_src sh
"pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-volume {} -5% && pkill -RTMIN+1 i3blocks"
Alt + b:5
#+end_src
** Workspace navigation with the mouse
*** Previous workspace
#+begin_src sh
"~/.config/scripts/navigate2ws_next.py --previous"
Control + b:1
#+end_src
*** Next workspace
#+begin_src sh
"~/.config/scripts/navigate2ws_next.py --next"
Control + b:3
#+end_src
** Window opacity with mouse
*** All windows
**** Increase opacity
#+begin_src sh
"$HOME/.config/scripts/picop.sh all +10"
mod5 + b:4
#+end_src
**** Decrease opacity
#+begin_src sh
"$HOME/.config/scripts/picop.sh all -10"
mod5 + b:5
#+end_src
*** Current window only
**** Increase opacity
#+begin_src sh
"$HOME/.config/scripts/picop.sh current +10"
mod3 + b:4
#+end_src
**** Decrease opacity
#+begin_src sh
"$HOME/.config/scripts/picop.sh current -10"
mod3 + b:5
#+end_src
* xcape
Launched in =$HOME/.xprofile=.

#+begin_src sh
xcape -e 'Alt_L=Page_Down;Hyper_L=Page_Up'
#+end_src
** PgUp / Hyper
#+begin_src sh
- Ctrl:
  - Tap: Page Up
  - Hold: Hyper_L (mapped as Ctrl in Xmodmap file)
#+end_src
** PgDn / Alt
#+begin_src sh
- Alt:
  - Tap: Page Down
  - Hold: Alt
#+end_src
