#+TITLE: Config file for xremap
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :noweb-sep "\n\n"
#+DESCRIPTION: config file for xremap
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc:
- [[#information][Information]]
  - [[#table][Table]]
  - [[#fn-keys][Fn keys]]
  - [[#workspace-navigation][Workspace navigation]]
  - [[#move-to-workspace][Move to workspace]]
  - [[#keeb-misc-layer][Keeb "misc" layer]]
- [[#modifiers][Modifiers]]
- [[#shared][Shared]]
  - [[#terminals][Terminals]]
  - [[#scratchpads][Scratchpads]]
  - [[#emacs-over-ssh][Emacs over SSH]]
  - [[#browsers][Browsers]]
  - [[#cedilla][Cedilla]]
- [[#modmap][Modmap]]
  - [[#btn_back-mouse][BTN_BACK [mouse]]]
  - [[#btn_forward-mouse][BTN_FORWARD [mouse]]]
  - [[#btn_side-mouse][BTN_SIDE [mouse]]]
- [[#keymap][Keymap]]
  - [[#modes][Modes]]
  - [[#cpc-copypastecut][CPC: Copy/Paste/Cut]]
  - [[#emacs-inhabitant][Emacs inhabitant]]
  - [[#emacs-over-ssh-1][Emacs over SSH]]
  - [[#kitty][Kitty]]
  - [[#terminals-1][Terminals]]
  - [[#browser][Browser]]
  - [[#cedilla-1][Cedilla]]
  - [[#dead-acute][Dead acute]]
  - [[#emote-navigation][Emote navigation]]
  - [[#capslock][Capslock]]
  - [[#system-control][System control]]
  - [[#scratchpad-navigation][Scratchpad navigation]]
  - [[#miscellaneous][Miscellaneous]]
  - [[#pdfpc][pdfpc]]
  - [[#libreoffice][LibreOffice]]
  - [[#mouse-controller][Mouse controller]]

* Information
** Table
|----------------+------------------+---------+---------------------+------------------------|
| Key name       | Xmodmap          | keycode | input-event-codes.h | used for               |
|----------------+------------------+---------+---------------------+------------------------|
| left shift     | Shift_L          |      42 | KEY_LEFTSHIFT       | shift (xkb)            |
| right shift    | Shift_R          |      54 | KEY_RIGHTSHIFT      | shift (xkb)            |
|----------------+------------------+---------+---------------------+------------------------|
| left ctrl      | Control_L        |      29 | KEY_LEFTCTRL        | control (xkb)          |
| right ctrl     | Control_R        |      97 | KEY_RIGHTCTRL       | control (xkb)          |
|----------------+------------------+---------+---------------------+------------------------|
| left alt       | Alt_L            |      56 | KEY_LEFTALT         | mod1 (xkb)             |
| right alt      | ISO_Level3_Shift |     100 | KEY_RIGHTALT        | mod5 (xkb)             |
|----------------+------------------+---------+---------------------+------------------------|
| win/super/meta | Super_L          |     125 | KEY_LEFTMETA        | mod4 (xkb)             |
| ???            | Super_R          |     126 | KEY_RIGHTMETA       | mod4 (xkb)             |
|----------------+------------------+---------+---------------------+------------------------|
| ???            | Hyper_L          |         | ?????               | ?????                  |
|----------------+------------------+---------+---------------------+------------------------|
| F13            | XF86Tools        |     183 | KEY_F13             | apostrophe             |
| F14            | XF86Launch5      |     184 | KEY_F14             | microphone             |
| F15            | XF86Launch6      |     185 | KEY_F15             | volume                 |
| F16            | XF86Launch7      |     186 | KEY_F16             | cut/copy/paste         |
| F17            | XF86Launch8      |     187 | KEY_F17             | cut/copy/paste (Emacs) |
| F18            | XF86Launch9      |     188 | KEY_F18             | ---                    |
| F19            | -----            |     189 | KEY_F19             | luminosity             |
| F20            | -----            |     190 | KEY_F20             | backlit & underglow    |
| F21            | -----            |     191 | KEY_F21             | [mouse] volume ctl     |
| F22            | -----            |     192 | KEY_F22             | [mouse] zoom ctl       |
| F23            | -----            |     193 | KEY_F23             | [mouse] brightness ctl |
| F24            | -----            |     194 | KEY_F24             | ---                    |
|----------------+------------------+---------+---------------------+------------------------|
| Power button   | XF86PowerOff     |     124 | KEY_POWER           | i3/sway mode_system    |
|----------------+------------------+---------+---------------------+------------------------|
** Fn keys
*** F13
Apostrophe - single/double quotes (xremap).
*** F14
Microphone (Oryx/QMK and xremap)
|------------------+-------------|
| binding          | description |
|------------------+-------------|
| F14              | mic- coarse |
| ctrl-F14         | mic+ coarse |
| shift-F14        | mic- fine   |
| shift-ctrl-F14   | mic+ fine   |
| meta-F14         | mic 50%     |
| XF86AudioMicMute | mic mute    |
|------------------+-------------|
*** F15
Volume (Oryx/QMK and xremap):
  - speaker
  - microphone
|-----------------+-------------|
| binding         | description |
|-----------------+-------------|
| F15-k           | vol toggle  |
| F15-e           | vol- coarse |
| F15-i           | vol+ coarse |
| S-F15-e         | vol- fine   |
| S-F15-i         | vol+ fine   |
| F15-comma       | vol- fine   |
| F15-dot         | vol+ fine   |
| F15-esc         | vol 0%      |
| F15-space       | vol 25%     |
| F15-tab         | vol 50%     |
| F15-enter       | vol 75%     |
| F15-backspace   | vol 100%    |
|-----------------+-------------|
| F15-j           | mic toggle  |
| F15-u           | mic- coarse |
| F15-y           | mic+ coarse |
| S-F15-u         | mic- fine   |
| S-F15-y         | mic+ fine   |
| S-F15-esc       | mic 0%      |
| S-F15-space     | mic 25%     |
| S-F15-tab       | mic 50%     |
| S-F15-enter     | mic 75%     |
| S-F15-backspace | mic 100%    |
|-----------------+-------------|
*** F16
Cut, copy, and paste.
|---------+-------------|
| binding | description |
|---------+-------------|
| M-F16   | cut         |
| S-F16   | copy        |
| C-F16   | paste       |
|---------+-------------|
*** F17
Cut, copy, and paste (Emacs edition).
|---------+------------------|
| binding | description      |
|---------+------------------|
| M-F17   | M-x              |
| S-F17   | evil-yank        |
| C-F17   | evil-paste-after |
|---------+------------------|
*** F18
TBD
*** F19
Luminosity (Oryx/QMK and xremap):
  - brightness
  - backlit
  - opacity
  - underglow LED
  - monitor LED strip (TBD)
|---------------+---------------------------------|
| binding       | description                     |
|---------------+---------------------------------|
| F19-e         | brightness- coarse              |
| F19-i         | brightness+ coarse              |
| S-F19-e       | brightness- fine                |
| S-F19-i       | brightness+ fine                |
| F19-esc       | brightness 0%                   |
| F19-space     | brightness 25%                  |
| F19-tab       | brightness 50%                  |
| F19-enter     | brightness 75%                  |
| F19-backspace | brightness 100%                 |
|---------------+---------------------------------|
| F19-h         | stop IWT && opacity current dec |
| F19-slash     | stop IWT && opacity current inc |
| S-F19-h       | stop IWT && opacity all dec     |
| S-F19-slash   | stop IWT && opacity all inc     |
| F19-k         | run IWT with --opacity 0.85     |
|---------------+---------------------------------|
| F19-comma     | backlit-                        |
| F19-dot       | backlit+                        |
| F19-d         | backlit toggle                  |
|---------------+---------------------------------|
| F19-n         | gamma-                          |
| F19-o         | gamma+                          |
| F19-m         | gamma toggle                    |
|---------------+---------------------------------|
| F19-l         | LED strip-                      |
| F19-f         | LED strip+                      |
| F19-j         | LED strip toggle                |
|---------------+---------------------------------|
| F19-u         | underglow LED-                  |
| F19-y         | underglow LED+                  |
| F19-v         | underglow LED toggle            |
|---------------+---------------------------------|
obs.: IWT = inactive-windows-transparency.py
*** F20
Keyboard backlit and underglow LEDs
|----------------+---------------------------|
| binding        | description               |
|----------------+---------------------------|
| F20            | keyboard backlit-         |
| ctrl-F20       | keyboard backlit+         |
| shift-F20      | @TBD: keyboard underglow- |
| shift-ctrl-F20 | @TBD: keyboard underglow+ |
| meta-F20       | keyboard backlit on/off   |
|----------------+---------------------------|
*** F21
Volume control with MX Master 3 mouse.
|-------------------+-----------------|
| binding           | description     |
|-------------------+-----------------|
| F21               | PageDown        |
| F21-wheel up      | vol+ coarse     |
| F21-wheel down    | vol- coarse     |
| F21-left click    | vol- (prev 25%) |
| F21-right click   | vol+ (next 25%) |
| F21-middle click  |                 |
| F21-mode shift    |                 |
|-------------------+-----------------|
| F21-gesture down  |                 |
| F21-gesture up    |                 |
| F21-gesture left  |                 |
| F21-gesture right |                 |
|-------------------+-----------------|
*** F22
Zoom control with MX Master 3 mouse.
|-------------------+-------------|
| binding           | description |
|-------------------+-------------|
| F22               | PageUp      |
| F22-wheel up      | zoom+ (C-+) |
| F22-wheel down    | zoom- (C--) |
| F22-left click    | ws prev     |
| F22-right click   | ws next     |
| F22-middle click  |             |
| F22-mode shift    |             |
|-------------------+-------------|
| F22-gesture down  |             |
| F22-gesture up    |             |
| F22-gesture left  |             |
| F22-gesture right |             |
|-------------------+-------------|
*** F23
Brightness control with MX Master 3 mouse.
|-------------------+--------------|
| binding           | description  |
|-------------------+--------------|
| F23               | enter        |
| F23-wheel up      | brightness+  |
| F23-wheel down    | brightness-  |
| F23-left click    | video speed- |
| F23-right click   | video speed+ |
| F23-middle click  | video speed= |
| F23-mode shift    |              |
|-------------------+--------------|
| F23-gesture down  |              |
| F23-gesture up    |              |
| F23-gesture left  |              |
| F23-gesture right |              |
|-------------------+--------------|
*** F24
TBD (suggestion: monitor LED strip)
*** FN_Fx
|---------+-------------------------------------|
| binding | description                         |
|---------+-------------------------------------|
| FN_F1   | switch xremap's mode to =lan-mouse=   |
| FN_F2   | switch xremap's mode to =default=     |
| FN_F3   | host control with MX Master 3 mouse |
|---------+-------------------------------------|
** Workspace navigation
|---------------------------+-----------------------|
| binding                   | description           |
|---------------------------+-----------------------|
| Super_L   + {1,2,...,9,0} | navigate to output #0 |
| S-Super_L + {1,2,...,9,0} | navigate to output #1 |
| Super_R   + {1,2,...,9,0} | navigate to output #2 |
|---------------------------+-----------------------|
** Move to workspace
|-----------------------------+-------------------|
| binding                     | description       |
|-----------------------------+-------------------|
| C-Super_L   + {1,2,...,9,0} | move to output #0 |
| C-S-Super_L + {1,2,...,9,0} | move to output #1 |
| C-Super_R   + {1,2,...,9,0} | move to output #2 |
|-----------------------------+-------------------|
** Keeb "misc" layer
|-----------+----------+-------------|
| binding   | category | description |
|-----------+----------+-------------|
| Alt_R + a | symbol   | ª           |
| Alt_R + o | symbol   | º           |
| Alt_R + p | currency | £           |
| Alt_R + e | currency | €           |
| Alt_R + y | currency | ￥          |
| Alt_R + r | currency | ₽           |
| Alt_R + s | macro    | address_1   |
| Alt_R + t | macro    | address_2   |
| Alt_R + c | macro    | zip_code    |
| Alt_R + d | macro    | phone       |
| Alt_R + n | macro    | email_1     |
| Alt_R + l | macro    | email_2     |
| Alt_R + u | macro    | email_3     |
| Alt_R + h | macro    | name        |
| Alt_R + i | macro    | id          |
|-----------+----------+-------------|
* Modifiers
*** i3wm
#+begin_src conf :noweb-ref i3-modifiers
virtual_modifiers:
  - F21
  - F22
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-modifiers
virtual_modifiers:
  - F15
  - F19
  - F21
  - F22
  - F23
#+end_src
* Shared
#+begin_src conf :noweb-ref shared-common
shared:
#+end_src
** Terminals
#+begin_src conf :noweb-ref shared-common
  terminals: &terminals
    - kitty
    - dropdown_terminal
    - dropdown_python
#+end_src
** Scratchpads
#+begin_src conf :noweb-ref shared-common
  scratchpads: &scratchpads
    - dropdown_terminal
    - dropdown_python
    - scrcpy
    - Brave-browser-beta
    - Keymapp
    - keymapp
#+end_src
** Emacs over SSH
#+begin_src conf :noweb-ref shared-common
  emacs-ssh: &emacs-ssh
    - "/.*: emacsclient --create-frame.* --alternate-editor=.*emacs.*/"
    - "/.*: emacsclient -c.* -a .*emacs.*/"
    - "/.*: ecd/"
    - "/.*: ec/"
#+end_src
** Browsers
#+begin_src conf :noweb-ref shared-common
  browsers: &browsers
    - "/brave.*/"
    - "/firefox.*/"
    - chromium
#+end_src
** Cedilla
Obs.: Sway only
#+begin_src conf :noweb-ref shared-sway
  cedilla: &cedilla
    - "/brave.*/"
    - chromium
#+end_src
* Modmap
#+begin_src conf :noweb-ref modmap
modmap:
#+end_src
** BTN_BACK [mouse]
tap: PageDown / hold: volume control (F21)
#+begin_src conf :noweb-ref modmap
  - name: volume control with side-bottom mouse button
    remap:
      BTN_BACK:
        held: F21
        alone: KEY_PAGEDOWN
        alone_timeout_millis: 200
#+end_src
** BTN_FORWARD [mouse]
tap: PageUp / hold: zoom control (F22)
#+begin_src conf :noweb-ref modmap
  - name: zoom control with side-top mouse button
    remap:
      BTN_FORWARD:
        held: F22
        alone: KEY_PAGEUP
        alone_timeout_millis: 200
#+end_src
** BTN_SIDE [mouse]
tap: Enter / hold: brightness control (F23)
#+begin_src conf :noweb-ref modmap
  - name: brightness control with mode shift mouse button
    remap:
      BTN_SIDE:
        held: F23
        alone: BTN_SIDE
        alone_timeout_millis: 200
#+end_src
* Keymap
#+begin_src conf :noweb-ref keymap
keymap:
#+end_src
** Modes
*** Default
#+begin_src conf :noweb-ref modes
  - name: enter lan-mouse mode (enable keybindings bypass)
    mode: default
    remap:
      # enter "lan-mouse" mode
      FN_F1:
        - { set_mode: lan-mouse }
        - { launch: ["swaymsg", "exec", "echo lan-mouse > /tmp/xremap_mode.tmp"] }
#+end_src
*** lan-mouse
#+begin_src conf :noweb-ref modes
  - name: disable lan-mouse bypass
    mode: lan-mouse
    remap:
      # return to "default" mode
      FN_F2:
        - { set_mode: default }
        - { launch: ["swaymsg", "exec", "echo default > /tmp/xremap_mode.tmp"] }
#+end_src
** CPC: Copy/Paste/Cut
*** Terminal
#+begin_src conf :noweb-ref cpc-terminal
  - name: copy/paste/cut - terminal
    application:
      only: *terminals
    remap:
      Alt_L-F16: Ctrl-Shift-x  # cut
      Shift-F16: Ctrl-Shift-c  # copy
      Ctrl-F16:  Ctrl-Shift-v  # paste
    mode: default
#+end_src
*** Emacs
#+begin_src conf :noweb-ref cpc-default
  - name: copy/paste/cut - general
    application:
      only: [Emacs, "/emacs.*/"]
    remap:
      Alt_L-F16: Alt_L-F17  # M-x
      Shift-F16: Shift-F17  # copy
      Ctrl-F16: Ctrl-F17    # paste
    mode: default
#+end_src
*** Default
#+begin_src conf :noweb-ref cpc-default
  - name: copy/paste/cut - general
    application:
      not: [Emacs, "/emacs.*/", libreoffice-calc]
    remap:
      Alt_L-F16: Ctrl-x  # cut
      Shift-F16: Ctrl-c  # copy
      Ctrl-F16: Ctrl-v   # paste
    mode: default
#+end_src
** Emacs inhabitant
*** i3wm
#+begin_src conf :noweb-ref i3-navigation
  - name: Emacs inhabitant
    exact_match: true
    application:
      not: [Emacs, "/emacs.*/"]
    remap:
      # window navigation
      Super_L-left:  { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh left"] }
      Super_L-down:  { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh down"] }
      Super_L-up:    { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh up"] }
      Super_L-right: { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh right"] }
      # fullscreen
      #Alt_L-Super_L-f:  { launch: ["bash", "-c", "i3-msg", "fullscreen", "toggle"] }
      Alt_L-Super_L-f:  { launch: ["i3-msg", "fullscreen", "toggle"] }
      # terminal
      #Alt_L-Super_L-t:  { launch: ["bash", "-c", "i3-msg", "exec", "kitty"] }
      Alt_L-Super_L-g:  { launch: ["i3-msg", "exec", "kitty"] }
      # kill window
      #Alt_L-Super_L-q:  { launch: ["bash", "-c", "i3-msg", "exec", "$XDG_CONFIG_HOME/scripts/hide-or-kill.sh"] }
      Alt_L-Super_L-q:  { launch: ["i3-msg", "exec", "$XDG_CONFIG_HOME/scripts/hide-or-kill.sh"] }
    mode: default
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-navigation
  - name: Emacs inhabitant
    exact_match: true
    application:
      not: [Emacs, "/emacs.*/"]
    remap:
      # window navigation
      Super_L-left:  { launch: ["swaymsg", "focus", "left"] }
      Super_L-down:  { launch: ["swaymsg", "focus", "down"] }
      Super_L-up:    { launch: ["swaymsg", "focus", "up"] }
      Super_L-right: { launch: ["swaymsg", "focus", "right"] }
      # fullscreen
      Alt_L-Super_L-f:  { launch: ["swaymsg", "fullscreen", "toggle"] }
      # terminal
      Alt_L-Super_L-g:  { launch: ["swaymsg", "exec", "kitty"] }
      # kill window
      Alt_L-Super_L-q:  { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/hide-or-kill.sh"] }
    mode: default
#+end_src
** Emacs over SSH
*** Window navigation
#+begin_src conf :noweb-ref emacs-ssh
  - name: Window navigation
    exact_match: true
    application:
      only: kitty
    window:
      only: *emacs-ssh
    remap:
      Super_L-left:  [C-w, C-h]
      Super_L-down:  [C-w, C-j]
      Super_L-up:    [C-w, C-k]
      Super_L-right: [C-w, C-l]
    mode: default
#+end_src
** Kitty
*** Delete word
#+begin_src conf :noweb-ref kitty
  - name: delete next word
    application:
      only: kitty
    remap:
      Ctrl-Shift-Backspace: Ctrl-Delete
    mode: default
#+end_src
*** Navigation
:PROPERTIES:
:header-args: :noweb-sep "\n"
:END:
#+begin_src conf :noweb-ref kitty
  - name: arrow up/down
    application:
      only: kitty
    remap:
#+end_src
**** Arrows
#+begin_src conf :noweb-ref kitty
      Ctrl-n: left
      Ctrl-e: down
      Ctrl-i: up
      Ctrl-o: right
#+end_src
**** Beginning/End of line
#+begin_src conf :noweb-ref kitty
      Alt-n: home
      Alt-o: end
#+end_src
**** Fix window properties snapshot
#+begin_src conf :noweb-ref kitty
      Ctrl-Alt-n: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/wlprop.sh focused"] }
#+end_src
**** EoS :noexport:
#+begin_src conf :noweb-sep "\n\n" :noweb-ref kitty
    mode: default
#+end_src
** Terminals
*** Zoom control
#+begin_src conf :noweb-ref kitty
  - name: terminal zoom with mouse
    application:
      only: *terminals
    remap:
      F22-XDOWNSCROLL: Ctrl-Shift-minus
      F22-XUPSCROLL:   Ctrl-Shift-equal
    mode: default
#+end_src
** Browser
*** All
**** Previous tab
#+begin_src conf :noweb-ref browsers
  - name: Prev tab
    exact_match: true
    application:
      only: *browsers
    remap:
      Ctrl-space: Shift-Ctrl-Tab
    mode: default
#+end_src
*** Brave
**** Tab navigation with on forbidden pages (Surfingkeys)
#+begin_src conf :noweb-ref surfingkeys
  - name: Prev/Next tab
    exact_match: true
    application:
      only: brave-browser
    window:
      only: ["better onetab - Brave", "Extensions - Brave", "chrome://newtab - Brave", "Chrome Web Store - Brave"]
    remap:
      Shift-N: Alt-Left        # go back
      Shift-E: Ctrl-Tab        # next tab
      Shift-I: Ctrl-Shift-Tab  # previous tab
      Shift-O: Alt-Right       # go forward
      Shift-X: Ctrl-Shift-T    # reopen tab
    mode: default
#+end_src
*** Firefox
#+begin_src conf :noweb-ref browsers
  - name: open browser in private window
    # Firefox
    application:
      only: firefox-developer-edition
    remap:
      Ctrl-Shift-n:
        # remap to C-S-p
        launch: ["bash", "-c", "ydotool key 29:1 42:1 25:1 25:0 42:0 29:0"]
    mode: default
#+end_src
** Cedilla
#+begin_src conf :noweb-ref cedilla
  - name: cedilla
    application:
      only: *cedilla
    remap:
      F13:
        remap:
          c:       { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"ç\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
          Shift-c: { launch: ["swaymsg", "exec", "sleep 0.1 && echo -n \"Ç\" | wl-copy && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
    mode: default
#+end_src
** Dead acute
:PROPERTIES:
:header-args: :noweb-sep "\n"
:END:
#+begin_src conf :noweb-ref dead-acute
  - name: forward char / dead_acute
    exact_match: true
    application:
      not: [Emacs, "/emacs.*/"]
    remap:
#+end_src
*** F13
#+begin_src conf :noweb-ref dead-acute
      F13:
        remap:
#+end_src
**** Apostrophe
#+begin_src conf :noweb-ref dead-acute
          # apostrophe
          F13: [APOSTROPHE, SPACE]
          space: [APOSTROPHE, SPACE]
#+end_src
**** Cedilla
#+begin_src conf :noweb-ref dead-acute
          # cedilla
          c: [APOSTROPHE, c]
          Shift-c: [APOSTROPHE, Shift-c]
#+end_src
**** Vowel lowercase
#+begin_src conf :noweb-ref dead-acute
          # lowercase vowels
          a: [APOSTROPHE, a]
          e: [APOSTROPHE, e]
          i: [APOSTROPHE, i]
          o: [APOSTROPHE, o]
          u: [APOSTROPHE, u]
#+end_src
**** Vowel uppercase
#+begin_src conf :noweb-ref dead-acute
          # uppercase vowels
          Shift-a: [APOSTROPHE, Shift-a]
          Shift-e: [APOSTROPHE, Shift-e]
          Shift-i: [APOSTROPHE, Shift-i]
          Shift-o: [APOSTROPHE, Shift-o]
          Shift-u: [APOSTROPHE, Shift-u]
#+end_src
**** Misc lowercase
#+begin_src conf :noweb-ref dead-acute
          # miscellaneous lowercase
          l: [APOSTROPHE, SPACE, l]
          n: [APOSTROPHE, SPACE, n]
          m: [APOSTROPHE, SPACE, m, SPACE]
          r: [APOSTROPHE, SPACE, r]
          s: [APOSTROPHE, SPACE, s, SPACE]
          t: [APOSTROPHE, SPACE, t, SPACE]
#+end_src
**** Misc uppercase
#+begin_src conf :noweb-ref dead-acute
          # miscellaneous uppercase
          Shift-l: [APOSTROPHE, SPACE, Shift-l]
          Shift-n: [APOSTROPHE, SPACE, Shift-n]
          Shift-m: [APOSTROPHE, SPACE, Shift-m, SPACE]
          Shift-r: [APOSTROPHE, SPACE, Shift-r]
          Shift-s: [APOSTROPHE, SPACE, Shift-s, SPACE]
          Shift-t: [APOSTROPHE, SPACE, Shift-t, SPACE]
#+end_src
*** Shift-F13
#+begin_src conf :noweb-ref dead-acute
      Shift-F13:
        remap:
#+end_src
**** Double quotes
#+begin_src conf :noweb-ref dead-acute
          # double quotes
          F13: [Shift-APOSTROPHE, SPACE]
          space: [Shift-APOSTROPHE, SPACE]
          #Shift-F13: [Shift-APOSTROPHE, SPACE]
#+end_src
**** Tilde lowercase
#+begin_src conf :noweb-ref dead-acute
          # tilde lowercase
          a: [Shift-GRAVE, a]
          o: [Shift-GRAVE, o]
          n: [Shift-GRAVE, n]
#+end_src
**** Tilde uppercase
#+begin_src conf :noweb-ref dead-acute
          # tilde uppercase
          Shift-A: [Shift-GRAVE, Shift-A]
          Shift-O: [Shift-GRAVE, Shift-O]
          Shift-N: [Shift-GRAVE, Shift-N]
#+end_src
**** Tilde misc
#+begin_src conf :noweb-ref dead-acute
          # tilde miscellaneous
          Shift-F13: [Shift-GRAVE, SPACE]
          SLASH:     [Shift-GRAVE, SPACE, SLASH]
          DOT:       [Shift-GRAVE, SPACE, SLASH, DOT]
#+end_src
**** Tilde paths
#+begin_src conf :noweb-ref dead-acute
          # tilde paths
          h: [Shift-GRAVE, SPACE, SLASH]
          g: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH]
          k: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH, k,e,e,b,a,b, SLASH]
          d: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH, d,o,t,f,i,l,e,s, SLASH]
          c: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH]
          e: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, e,m,a,c,s,minus,e,f,s, SLASH]
          s: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, s,c,r,i,p,t,s, SLASH]
          v: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, n,v,i,m, SLASH]
          x: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, x,r,e,m,a,p, SLASH]
          w: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, w,a,y,b,a,r, SLASH]
          z: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, z,s,h, SLASH]
#+end_src
***** i3wm/Sway
#+name: dead-acute-i3sway
#+begin_src emacs-lisp :var wm="s,w,a,y" :results raw
(format "          i: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, %s, SLASH]" wm)
#+end_src
*** EoS :noexport:
#+begin_src conf :noweb-ref dead-acute-eos
    mode: default
#+end_src
** Emote navigation
:PROPERTIES:
:header-args: :noweb-sep "\n"
:END:
*** Navigation
#+begin_src conf :noweb-ref emote
  - name: navigate through emoji categories
    application:
      only: [emote, Emote]
    remap:
      Shift-N: Ctrl-Shift-Tab  # previous category
      Shift-O: Ctrl-Tab        # next category
      Shift-I: Ctrl-F          # focus search
      Ctrl-n:  left            # arrow left
      Ctrl-e:  down            # arrow down
      Ctrl-i:  up              # arrow up
      Ctrl-o:  right           # arrow right
#+end_src
*** Select and paste
#+begin_src conf :noweb-ref emote
      # launch script that will:
      #   - copy emoji (S-Enter)
      #   - exit emote (Esc)
      #   - paste according to context
      Enter: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/emote-paste.sh"] }
#+end_src
*** EoS :noexport:
#+begin_src conf :noweb-ref emote
    mode: default
#+end_src
** Capslock
#+begin_src conf :noweb-ref capslock
  - name: toggle capslock status & update temp file (/tmp/capslock_status.tmp)
    remap:
      CAPSLOCK: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/capslock-status.sh toggle"] }
    mode: default
#+end_src
** System control
:PROPERTIES:
:header-args: :noweb-sep "\n"
:END:
*** Media
**** Speaker
#+begin_src conf :noweb-ref control
  - name: speaker control
    exact_match: true
    remap:
#+end_src
***** Toggle
#+begin_src conf :noweb-ref control
      F15-k:         { launch: ["bash", "-c", "amixer -q sset Master toggle"] }
#+end_src
***** Levels
#+begin_src conf :noweb-ref control
      F15-esc:       { launch: ["bash", "-c", "amixer -q sset Master 0%"] }
      F15-space:     { launch: ["bash", "-c", "amixer -q sset Master 25%"] }
      F15-tab:       { launch: ["bash", "-c", "amixer -q sset Master 50%"] }
      F15-enter:     { launch: ["bash", "-c", "amixer -q sset Master 75%"] }
      F15-backspace: { launch: ["bash", "-c", "amixer -q sset Master 100%"] }
#+end_src
***** Coarse
#+begin_src conf :noweb-ref control
      F15-e:         { launch: ["bash", "-c", "amixer -q sset Master 5%-"] }
      F15-i:         { launch: ["bash", "-c", "amixer -q sset Master 5%+"] }
#+end_src
***** Fine
#+begin_src conf :noweb-ref control
      Shift-F15-e:   { launch: ["bash", "-c", "amixer -q sset Master 1%-"] }  # not working on IPF laptop due to hardware limitations (key ghosting)
      Shift-F15-i:   { launch: ["bash", "-c", "amixer -q sset Master 1%+"] }
      F15-comma:     { launch: ["bash", "-c", "amixer -q sset Master 1%-"] }
      F15-dot:       { launch: ["bash", "-c", "amixer -q sset Master 1%+"] }
#+end_src
***** EoS :noexport:
#+begin_src conf :noweb-ref control :noweb-sep "\n\n"
    mode: default
#+end_src
**** Microphone
#+begin_src conf :noweb-ref control
  - name: microphone control
    remap:
#+end_src
***** Toggle
#+begin_src conf :noweb-ref control
      F15-j: { launch: ["bash", "-c", "amixer -q sset Capture toggle"] }
#+end_src
***** Levels
#+begin_src conf :noweb-ref control
      Alt-F15-esc:       { launch: ["bash", "-c", "amixer -q sset Capture 0%"] }
      Alt-F15-space:     { launch: ["bash", "-c", "amixer -q sset Capture 25%"] }
      Alt-F15-tab:       { launch: ["bash", "-c", "amixer -q sset Capture 50%"] }
      Alt-F15-enter:     { launch: ["bash", "-c", "amixer -q sset Capture 75%"] }
      Alt-F15-backspace: { launch: ["bash", "-c", "amixer -q sset Capture 100%"] }
#+end_src
***** Coarse
#+begin_src conf :noweb-ref control
      F15-u:         { launch: ["bash", "-c", "amixer -q sset Capture 5%-"] }
      F15-y:         { launch: ["bash", "-c", "amixer -q sset Capture 5%+"] }
#+end_src
***** Fine
#+begin_src conf :noweb-ref control
      Shift-F15-u:       { launch: ["bash", "-c", "amixer -q sset Capture 1%-"] }  # not working on IPF laptop due to hardware limitations (key ghosting)
      Shift-F15-y:       { launch: ["bash", "-c", "amixer -q sset Capture 1%+"] }
#+end_src
***** EoS :noexport:
#+begin_src conf :noweb-ref control :noweb-sep "\n\n"
    mode: default
#+end_src
**** YouTube speed control
#+begin_src conf :noweb-ref control
  - name: YouTube speed control
    remap:
#+end_src
***** Levels
#+begin_src conf :noweb-ref control :noweb-sep "\n\n"
      Shift-F15-esc:       j  # x1.00
      Shift-F15-space:     l  # x1.25
      Shift-F15-tab:       u  # x1.50
      Shift-F15-enter:     k  # x2.00
      Shift-F15-backspace: h  # x3.00
    mode: default
#+end_src
*** Luminosity
**** Brightness
#+begin_src conf :noweb-ref control
  - name: brightness control
    remap:
#+end_src
***** Levels
#+begin_src conf :noweb-ref control
      F19-esc:       { launch: ["bash", "-c", "brightnessctl set 0%"] }
      F19-space:     { launch: ["bash", "-c", "brightnessctl set 25%"] }
      F19-tab:       { launch: ["bash", "-c", "brightnessctl set 50%"] }
      F19-enter:     { launch: ["bash", "-c", "brightnessctl set 75%"] }
      F19-backspace: { launch: ["bash", "-c", "brightnessctl set 100%"] }
#+end_src
***** Coarse
#+begin_src conf :noweb-ref control
      F19-e:         { launch: ["bash", "-c", "brightnessctl set 5%-"] }
      F19-i:         { launch: ["bash", "-c", "brightnessctl set 5%+"] }
#+end_src
***** Fine
#+begin_src conf :noweb-ref control
      S-F19-e:       { launch: ["bash", "-c", "brightnessctl set 1%-"] }
      S-F19-i:       { launch: ["bash", "-c", "brightnessctl set 1%+"] }
#+end_src
***** EoS :noexport:
#+begin_src conf :noweb-ref control :noweb-sep "\n\n"
    mode: default
#+end_src
**** Opacity
#+begin_src conf :noweb-ref control
  - name: opacity control
    exact_match: true
    remap:
#+end_src
***** Current window
#+begin_src conf :noweb-ref control
      F19-h:       { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "current", "dec"] }
      F19-slash:   { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "current", "inc"] }
      F19-k:       { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "reset"] }
#+end_src
***** All windows
#+begin_src conf :noweb-ref control
      C-F19-h:     { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "all", "dec"] }
      C-F19-slash: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/opacity.sh", "all", "inc"] }
#+end_src
***** EoS :noexport:
#+begin_src conf :noweb-ref control :noweb-sep "\n\n"
    mode: default
#+end_src
**** Backlit
#+begin_src conf :noweb-ref control
  - name: backlit control
    remap:
      F19-d:     { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/keeb-backlit.sh", "toggle"] }
      F19-comma: { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/keeb-backlit.sh", "dec"] }
      F19-dot:   { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/keeb-backlit.sh", "inc"] }
    mode: default
#+end_src
** Scratchpad navigation
#+name: scratchpad-navigation
#+begin_src emacs-lisp :var ipc_cmd="swaymsg" :results raw
(concat
  (format "  - name: window navigation from scratchpads\n")
  (format "    application:\n")
  (format "      only: *scratchpads\n")
  (format "    remap:\n")
  (format "      Super-Left:  { launch: [\"%s\", \"focus\", \"output\", \"left\"] }\n" ipc_cmd)
  (format "      Super-Right: { launch: [\"%s\", \"focus\", \"output\", \"right\"] }\n" ipc_cmd)
)
#+end_src
** Miscellaneous
*** Macros (terminal)
#+name: macros-terminal
#+begin_src emacs-lisp :var ipc_cmd="swaymsg" copy_cmd="wl-copy" :results raw
(concat
  (format "  - name: miscellaneous text - macros (terminal)\n")
  (format "    application:\n")
  (format "      only: *terminals\n")
  (format "    remap:\n")
  (format "      # macro\n")
  (format "      Alt_R-s: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/address_1)\\\" | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-t: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/address_2)\\\" | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-g: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/address_3)\\\" | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-c: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/zip_code)\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-d: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/phone)\\\"     | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-n: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/email_1)\\\"   | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-l: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/email_2)\\\"   | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-u: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/email_3)\\\"   | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-h: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/name)\\\"      | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-i: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"$(<$XDG_CONFIG_HOME/macros/id)\\\"        | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
)
#+end_src
*** Macros
#+name: macros
#+begin_src emacs-lisp :var ipc_cmd="swaymsg" copy_cmd="wl-copy" :results raw
(concat
  (format "  - name: miscellaneous text - macros\n")
  (format "    application:\n")
  (format "      not: *terminals\n")
  (format "    remap:\n")
  (format "      # macro\n")
  (format "      Alt_R-s: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_1 | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-t: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_2 | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-g: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_3 | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-c: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/zip_code  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-d: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/phone     | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-n: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_1   | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-l: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_2   | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-u: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_3   | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-h: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/name      | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-i: { launch: [\"%s\", \"exec\", \"sleep 0.1 && cat $XDG_CONFIG_HOME/macros/id        | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
)
#+end_src
*** Currency & symbol (terminal)
#+name: currency-symbol-terminal
#+begin_src emacs-lisp :var ipc_cmd="swaymsg" copy_cmd="wl-copy" :results raw
(concat
  (format "  - name: miscellaneous text - currency & symbol (terminal)\n")
  (format "    application:\n")
  (format "      only: *terminals\n")
  (format "    remap:\n")
  (format "      # currency\n")
  (format "      Alt_R-e: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"€\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-p: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"£\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-y: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"￥\\\" | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-r: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"₽\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      # symbol\n")
  (format "      Alt_R-a: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"ª\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-o: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"º\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-q: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"⌀\\\"  | %s && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0\"] }\n" ipc_cmd copy_cmd)
)
#+end_src
*** Currency & symbol
#+name: currency-symbol
#+begin_src emacs-lisp :var ipc_cmd="swaymsg" copy_cmd="wl-copy" :results raw
(concat
  (format "  - name: miscellaneous text - currency & symbol\n")
  (format "    application:\n")
  (format "      not: *terminals\n")
  (format "    remap:\n")
  (format "      # currency\n")
  (format "      Alt_R-e: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"€\\\"  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-p: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"£\\\"  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-y: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"￥\\\" | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-r: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"₽\\\"  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      # symbol\n")
  (format "      Alt_R-a: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"ª\\\"  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-o: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"º\\\"  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
  (format "      Alt_R-q: { launch: [\"%s\", \"exec\", \"sleep 0.1 && echo -n \\\"⌀\\\"  | %s && ydotool key 29:1 47:1 47:0 29:0\"] }\n" ipc_cmd copy_cmd)
)
#+end_src
** pdfpc
:PROPERTIES:
:header-args: :noweb-sep "\n"
:END:
#+begin_src conf :noweb-ref pdfpc
  - name: presentation with pdfpc
    exact_match: true
    application:
      only: pdfpc
    remap:
#+end_src
*** Home row: RST
#+begin_src conf :noweb-ref pdfpc
      KEY_R: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "camera"] }
      KEY_S: KEY_1
      KEY_T: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "presentation"] }
#+end_src
*** Top row: WFP
#+begin_src conf :noweb-ref pdfpc
      KEY_W: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-4"] }
      KEY_F: KEY_2
      KEY_P: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-6"] }
#+end_src
*** Bottom row: XCD
#+begin_src conf :noweb-ref pdfpc
      KEY_X: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-7"] }
      KEY_C: KEY_3
      KEY_D: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-9"] }
#+end_src
*** Right column: BGV
#+begin_src conf :noweb-ref pdfpc
      KEY_B: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--record"] }
      KEY_G: KEY_MINUS
      KEY_V: S-EQUAL
#+end_src
*** Right column: QAZ
#+begin_src conf :noweb-ref pdfpc
      KEY_Q: KEY_5
      KEY_A: KEY_4
      #KEY_Z:
#+end_src
*** Thumb cluster: Space, ESC, Tab
#+begin_src conf :noweb-ref pdfpc
      KEY_SPACE: KEY_DOWN
      KEY_ESC: KEY_UP
      #KEY_TAB:
#+end_src
*** EoS :noexport:
#+begin_src conf :noweb-ref pdfpc
    mode: default
#+end_src
** LibreOffice
:PROPERTIES:
:header-args: :noweb-sep "\n"
:END:
#+begin_src conf :noweb-ref libreoffice
  - name: LibreOffice custom bindings
    application:
      only: libreoffice-calc
    remap:
#+end_src
*** Navigation
#+begin_src conf :noweb-ref libreoffice
      #Ctrl-n: left       # navigation
      #Ctrl-e: down       # navigation
      #Ctrl-i: up         # navigation
      #Ctrl-o: right      # navigation
#+end_src
*** Copy/paste/cut
#+begin_src conf :noweb-ref libreoffice
      F16: Ctrl-x        # cut
      F17: Ctrl-Shift-c  # copy
      F18: Ctrl-v        # paste
#+end_src
*** Miscellaneous
#+begin_src conf :noweb-ref libreoffice
      #Alt-o: Ctrl-o      # open file
#+end_src
*** EoS :noexport:
#+begin_src conf :noweb-ref libreoffice
    mode: default
#+end_src
** Mouse controller
*** Side-bottom
**** Volume control
#+begin_src conf :noweb-ref mouse
  - name: volume control with mouse
    exact_match: true
    remap:
      F21-XDOWNSCROLL: { launch: ["bash", "-c", "amixer -q sset Master 1%-"] }
      F21-XUPSCROLL:   { launch: ["bash", "-c", "amixer -q sset Master 1%+"] }
      #F21-BTN_LEFT:    { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/volume-control.sh", "down", "25"] }
      #F21-BTN_RIGHT:   { launch: ["swaymsg", "exec", "$XDG_CONFIG_HOME/scripts/volume-control.sh", "up", "25"] }
      F21-BTN_LEFT:    Shift-Ctrl-Tab
      F21-BTN_RIGHT:   Ctrl-Tab
      F21-BTN_MIDDLE:  { launch: ["bash", "-c", "amixer -q sset Master 50%"] }
      F21-Enter:       { launch: ["bash", "-c", "amixer -q sset Master 98%"] }
    mode: default
#+end_src
**** Gestures
#+begin_src conf :noweb-ref mouse
  - name: placeholder for side-bottom button + mode shift gestures control with mouse
    exact_match: true
    remap:
      # down
      F21-F17:     { launch: ["bash", "-c", "amixer -q sset Master 11%"] }
      # up
      F21-F18:     { launch: ["bash", "-c", "amixer -q sset Master 22%"] }
      # left
      F21-Shift-n: { launch: ["bash", "-c", "amixer -q sset Master 33%"] }
      # right
      F21-Shift-o: { launch: ["bash", "-c", "amixer -q sset Master 44%"] }
    mode: default
#+end_src
*** Side-top
**** Zoom control
#+begin_src conf :noweb-ref mouse
  - name: zoom control with mouse
    exact_match: true
    remap:
      F22-XDOWNSCROLL: Ctrl-minus
      F22-XUPSCROLL:   Ctrl-Shift-equal
      F22-BTN_LEFT:    { launch: ["swaymsg", "workspace", "prev_on_output"] }
      F22-BTN_RIGHT:   { launch: ["swaymsg", "workspace", "next_on_output"] }
      F22-BTN_MIDDLE:  { launch: ["bash", "-c", "amixer -q sset Master 50%"] }
      F22-Enter:       { launch: ["bash", "-c", "amixer -q sset Master 76%"] }
    mode: default
#+end_src
**** Gestures
#+begin_src conf :noweb-ref mouse
  - name: placeholder for side-top button + mode shift gestures control with mouse
    exact_match: true
    remap:
      # down
      F22-F17:     { launch: ["bash", "-c", "amixer -q sset Master 55%"] }
      # up
      F22-F18:     { launch: ["bash", "-c", "amixer -q sset Master 66%"] }
      # left
      F22-Shift-n: { launch: ["bash", "-c", "amixer -q sset Master 77%"] }
      # right
      F22-Shift-o: { launch: ["bash", "-c", "amixer -q sset Master 88%"] }
    mode: default
#+end_src
*** Gesture button
**** Brightness control
#+begin_src conf :noweb-ref mouse
  - name: brightness control with mouse
    exact_match: true
    remap:
      F23-XDOWNSCROLL: { launch: ["bash", "-c", "brightnessctl set 5%-"] }
      F23-XUPSCROLL:   { launch: ["bash", "-c", "brightnessctl set 5%+"] }
    mode: default
#+end_src
**** Video speed control
#+begin_src conf :noweb-ref mouse
  - name: video speed control with mouse
    exact_match: true
    remap:
      F23-BTN_LEFT:    Shift-leftbrace   # decrease speed
      F23-BTN_RIGHT:   Shift-rightbrace  # increase speed
      F23-BTN_MIDDLE:  u                 # reset speed
      F23-Enter:       { launch: ["bash", "-c", "brightnessctl set 54%"] }
    mode: default
#+end_src
**** Gestures
#+begin_src conf :noweb-ref mouse
  - name: placeholder for gestures button + mode shift gestures control with mouse
    exact_match: true
    remap:
      # down
      F23-F17:     { launch: ["bash", "-c", "amixer -q sset Master 12%"] }
      # up
      F23-F18:     { launch: ["bash", "-c", "amixer -q sset Master 34%"] }
      # left
      F23-Shift-n: { launch: ["bash", "-c", "amixer -q sset Master 56%"] }
      # right
      F23-Shift-o: { launch: ["bash", "-c", "amixer -q sset Master 78%"] }
    mode: default
#+end_src
* Tangle :noexport:
** i3
#+begin_src conf :noweb yes :tangle config_i3.yml
<<i3-modifiers>>

<<shared-common>>

<<modmap>>

<<keymap>>

<<modes>>

<<cpc-terminal>>
<<cpc-emacs>>
<<cpc-default>>

<<i3-navigation>>
<<emacs>>
<<emacs-ssh>>

<<kitty>>

<<browsers>>

<<surfingkeys>>

<<dead-acute>>
<<dead-acute-i3sway(wm="i,\"3\"")>>
<<dead-acute-eos>>

<<emote>>

<<control>>

<<scratchpad-navigation(ipc_cmd="i3-msg")>>
<<macros-terminal(ipc_cmd="i3-msg", copy_cmd="xclip -sel clip")>>
<<macros(ipc_cmd="i3-msg", copy_cmd="xclip -sel clip")>>
<<currency-symbol-terminal(ipc_cmd="i3-msg", copy_cmd="xclip -sel clip")>>
<<currency-symbol(ipc_cmd="i3-msg", copy_cmd="xclip -sel clip")>>

#<<pdfpc>>

<<libreoffice>>

<<mouse>>
#+end_src
** Sway
#+begin_src conf :noweb yes :tangle config_sway.yml :results output
<<sway-modifiers>>

<<shared-common>>
<<shared-sway>>

<<modmap>>

<<keymap>>

<<modes>>

<<cpc-terminal>>
<<cpc-emacs>>
<<cpc-default>>

<<sway-navigation>>
<<emacs>>
<<emacs-ssh>>

<<kitty>>

<<browsers>>

<<surfingkeys>>

<<cedilla>>

<<dead-acute>>
<<dead-acute-i3sway(wm="s,w,a,y")>>
<<dead-acute-eos>>

<<emote>>
<<emote-sway>>
<<capslock>>

<<control>>

<<scratchpad-navigation(ipc_cmd="swaymsg")>>
<<macros-terminal(ipc_cmd="swaymsg", copy_cmd="wl-copy")>>
<<macros(ipc_cmd="swaymsg", copy_cmd="wl-copy")>>
<<currency-symbol-terminal(ipc_cmd="swaymsg", copy_cmd="wl-copy")>>
<<currency-symbol(ipc_cmd="swaymsg", copy_cmd="wl-copy")>>

#<<pdfpc>>

<<libreoffice>>

<<mouse>>
#+end_src
#+end_src
